### ISSUE TITLE
Failed to activate the Cozy-theme theme

### ISSUE THREAD

**Issue by jish** [exAspArk/cozy-atom-theme#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.200.0
**System**: Mac OS X 10.10.3
**Thrown From**: [Cozy-theme](https://github.com/exAspArk/cozy-atom-theme) package, v0.5.0
### Stack Trace

Failed to activate the Cozy-theme theme

```
At variable @syntax-bracket-matcher is undefined in /Users/josh/.atom/packages/Cozy-theme/index.less:56:20

LessError: variable @syntax-bracket-matcher is undefined
  at /Users/josh/.atom/packages/Cozy-theme/index.less:56:20
```
### Commands

```
     -0:10.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-Cozy-theme.theme-atom-light-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "Cozy-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by exAspArk** [comment]
Hey @jish,

Could you please check what do you have in `/Users/josh/.atom/packages/Cozy-theme/styles/syntax-variables.less`? Does it contain `@syntax-bracket-matcher: #666666;` at the end of the file?

Or can you try to uninstall and install it again?

**Comment by jish** [comment]
Yes, that line is present

```
﻿$ grep bracket .atom/packages/Cozy-theme/styles/syntax-variables.less
@syntax-bracket-matcher: #666666;
```

And it's working today. I don't if I needed to restart Atom or what. Works fine now! :)
